function ActionTypes()
	return {
		ADD_TODO: "ADD_TODO",
		TOGGLE_TODO: "TOGGLE_TODO",
		REMOVE_TODO: "REMOVE_TODO",
		ADD_TODOS: "ADD_TODOS",

		SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER"
	}
end function
